BugFix 836e0e4 - TypeError: 'type' object is not subscriptable
Fixing Bug introduced in 836e0e439bc3dc6f9fe91446a1e50bc3efe89e70 @cgarciae

```
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/kw_only_dataclasses.py", line 126, in <module>
    def _process_class(cls: type[M], extra_fields=None, **kwargs):
TypeError: 'type' object is not subscriptable
```

Small but of fairly wide implications, it's breaking a whole lot of code with the new release `0.7.3`